// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSO0ejT-yt8Y0uxpp1RornEOxRBbn1fw0',
    appId: '1:289539893496:web:a0c092e2c2afdab8e5730d',
    messagingSenderId: '289539893496',
    projectId: 'crudoperations-1bb67',
    authDomain: 'crudoperations-1bb67.firebaseapp.com',
    storageBucket: 'crudoperations-1bb67.appspot.com',
    measurementId: 'G-03HN9FPP2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHqK-sAtsOvnxrYPUSa3y3wxxqVGcs4Q',
    appId: '1:289539893496:android:ce3fb7d23384af20e5730d',
    messagingSenderId: '289539893496',
    projectId: 'crudoperations-1bb67',
    storageBucket: 'crudoperations-1bb67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHCeXHQrp5m3nEubHFja_8YdVFXeYNCQ',
    appId: '1:289539893496:ios:d4e92df0111156b6e5730d',
    messagingSenderId: '289539893496',
    projectId: 'crudoperations-1bb67',
    storageBucket: 'crudoperations-1bb67.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHCeXHQrp5m3nEubHFja_8YdVFXeYNCQ',
    appId: '1:289539893496:ios:d4e92df0111156b6e5730d',
    messagingSenderId: '289539893496',
    projectId: 'crudoperations-1bb67',
    storageBucket: 'crudoperations-1bb67.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSO0ejT-yt8Y0uxpp1RornEOxRBbn1fw0',
    appId: '1:289539893496:web:86e708591ab64de7e5730d',
    messagingSenderId: '289539893496',
    projectId: 'crudoperations-1bb67',
    authDomain: 'crudoperations-1bb67.firebaseapp.com',
    storageBucket: 'crudoperations-1bb67.appspot.com',
    measurementId: 'G-74MKN0QS09',
  );
}
